/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Số liệu tổng quan của sàn
         * @description Ba con số đọc được từ CSDL. Không có số liệu phát sóng ở đây: đường ghi
         *     bằng chứng phát sóng mới hoạt động từ giai đoạn 2 và chưa có dữ liệu.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                total_screens: number;
                                total_cities: number;
                                total_owners: number;
                            };
                        };
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bộ lọc tổng hợp cho trang khám phá
         * @description Dùng chung nguồn với bộ lọc trên trang công khai, nên hai nơi không
         *     thể hiện ra danh sách khác nhau. Khoảng giá lấy từ `floor_cpm` —
         *     chính con số trang công khai đang hiển thị.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                cities: components["schemas"]["FilterFacet"][];
                                venue_types: components["schemas"]["FilterFacet"][];
                                networks: components["schemas"]["FilterFacet"][];
                                owners: {
                                    slug?: string | null;
                                    name?: string | null;
                                    count?: number;
                                }[];
                                /**
                                 * @description Khoảng giá CPM, **chỉ tính hàng VND**. Bản đầu gọi
                                 *     nó là `price_range_vnd` trong khi MIN/MAX chạy trên
                                 *     toàn bộ `floor_cpm` bất kể `floor_cpm_currency`, nên
                                 *     một hàng USD kéo `min` xuống vài đơn vị (Codex R39).
                                 */
                                price_range: {
                                    /** @enum {string} */
                                    currency: "VND";
                                    min: number;
                                    max: number;
                                };
                            };
                        };
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/screens/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pin bản đồ trong một khung nhìn
         * @description **Khung nhìn bắt buộc.** Thiếu `north`/`south`/`east`/`west` là 422,
         *     không phải "mặc định cả thế giới": không có khung nhìn thì endpoint
         *     này là một lần xuất toàn bộ kho dưới cái tên vô hại.
         *
         *     Trên khung nhìn vẫn còn **giới hạn cứng** số pin, vì khung nhìn rộng
         *     vẫn có thể trùm cả kho. Khi bị cắt, `meta.truncated` là `true` và
         *     `meta.total` cho biết còn bao nhiêu — client thu nhỏ khung nhìn lại.
         *     Pin bị cắt được sắp thứ tự xác định, nên kéo bản đồ qua lại không ra
         *     tập pin khác nhau một cách vô cớ.
         *
         *     Bộ lọc giống hệt `/api/v2/screens`.
         */
        get: {
            parameters: {
                query: {
                    north: number;
                    south: number;
                    east: number;
                    west: number;
                    limit?: number;
                    q?: string;
                    city?: string[];
                    venue_type?: string[];
                    screen_type?: ("billboard" | "led" | "lcd")[];
                    network?: string[];
                    owner?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["MapPin"][];
                            meta: {
                                returned: number;
                                /** @description Tổng số pin khớp bộ lọc và khung nhìn, trước khi cắt. */
                                total: number;
                                limit: number;
                                max_limit: number;
                                truncated: boolean;
                                viewport: {
                                    north: number;
                                    south: number;
                                    east: number;
                                    west: number;
                                };
                            };
                        };
                    };
                };
                422: components["responses"]["ValidationFailed"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/screens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách màn hình
         * @description Phân trang có **giới hạn cứng**: `per_page` lớn hơn `max_per_page` bị
         *     kẹp về mức đó, không trả về toàn bộ kho.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    q?: string;
                    city?: string[];
                    province?: string[];
                    district?: string[];
                    region?: ("north" | "central" | "south")[];
                    venue_type?: string[];
                    screen_type?: ("billboard" | "led" | "lcd")[];
                    orientation?: ("landscape" | "portrait" | "square")[];
                    network?: string[];
                    owner?: string[];
                    site?: string;
                    min_price?: number;
                    max_price?: number;
                    sort?: "price_asc" | "price_desc" | "newest";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ScreenSummary"][];
                            meta: components["schemas"]["PageMeta"];
                        };
                    };
                };
                422: components["responses"]["ValidationFailed"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/screens/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết một màn hình */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ScreenSummary"] & {
                                availability: components["schemas"]["Availability"];
                            };
                        };
                    };
                };
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách media owner */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    q?: string;
                    /** @description Lọc theo loại điểm đặt của màn hình thuộc owner. */
                    type?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["OwnerSummary"][];
                            meta: components["schemas"]["PageMeta"];
                        };
                    };
                };
                422: components["responses"]["ValidationFailed"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/owners/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết media owner kèm màn hình của họ
         * @description Màn hình đi kèm dùng đúng `ScreenSummary` như `/api/v2/screens`, nên
         *     bên tiêu thụ chỉ cần một kiểu dữ liệu cho màn hình.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    city?: string[];
                    network?: string[];
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["OwnerDetail"];
                            screens: {
                                data: components["schemas"]["ScreenSummary"][];
                                meta: components["schemas"]["PageMeta"];
                            };
                        };
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationFailed"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách sản phẩm (gói và vị trí lẻ)
         * @description Dùng chung `ProductService` với trang `/products`, nên bộ lọc và thứ
         *     tự không thể khác nhau giữa hai nơi.
         *
         *     `owner` nhận **slug**, không nhận id nội bộ. Slug không tồn tại thì
         *     kết quả rỗng, không phải "bỏ qua bộ lọc và trả cả kho".
         *
         *     Tham số nhiều giá trị dùng `explode: false` (`category=led,lcd`) —
         *     xem ghi chú ở `/api/v2/screens` về vì sao không dùng `explode: true`.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    q?: string;
                    category?: ("billboard" | "led" | "lcd" | "posm" | "standee" | "escalator_wrap" | "ceiling_hang" | "lightbox")[];
                    type?: "single" | "package" | "custom";
                    city?: string[];
                    owner?: string;
                    min_price?: number;
                    max_price?: number;
                    sort?: "price_asc" | "price_desc" | "newest";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ProductSummary"][];
                            meta: components["schemas"]["PageMeta"];
                        };
                    };
                };
                422: components["responses"]["ValidationFailed"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết một sản phẩm */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ProductDetail"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Giỏ hàng hiện tại của người đang đăng nhập */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Cart"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Thêm một màn hình hoặc một sản phẩm vào giỏ
         * @description Gửi `screen_slug` để thêm một màn hình lẻ, hoặc `product_slug` để thêm
         *     một sản phẩm. API **không** nhận khóa nội bộ: trang Blade gửi
         *     `screen_id`/`product_id` vì nó dựng form từ model sẵn trong tay, còn
         *     client ngoài thì dùng slug và máy chủ quy đổi.
         *
         *     **Không nhận số tiền.** `estimated_cost` do `CartService` tính lại từ
         *     cấu hình kho; trường nào client gửi lên cũng bị bỏ qua.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Bắt buộc khi thêm một màn hình lẻ. */
                        screen_slug?: string;
                        /** @description Bắt buộc khi thêm một sản phẩm. */
                        product_slug?: string;
                        selected_screen_slugs?: string[];
                        /** @enum {string} */
                        buy_mode?: "package" | "individual";
                        /** Format: date */
                        start_date?: string;
                        /** Format: date */
                        end_date?: string;
                        quantity?: number;
                        /** @enum {string} */
                        pricing_model?: "cpm" | "io";
                        booked_cpms?: number;
                        duration_units?: number;
                    };
                };
            };
            responses: {
                /** @description Đã thêm */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Cart"] & {
                                added_item_id?: string;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationFailed"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/cart/items/{item}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Xóa một dòng giỏ */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    item: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Cart"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Sửa một dòng giỏ
         * @description Không có trường tiền nào. `estimated_cost` được tính lại từ cấu hình
         *     kho sau mỗi lần sửa — số tiền do máy chủ tính.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    item: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        start_date?: string;
                        /** Format: date */
                        end_date?: string;
                        share_of_voice_pct?: number;
                        spot_length?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Cart"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationFailed"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ScreenSummary: {
            slug: string;
            name: string;
            /** @enum {string} */
            screen_type: "billboard" | "led" | "lcd";
            owner: {
                slug?: string | null;
                name?: string | null;
            };
            location: {
                site?: string | null;
                city?: string | null;
                district?: string | null;
            };
            network?: {
                code?: string;
                name?: string;
            } | null;
            size: {
                width_m?: number | null;
                height_m?: number | null;
            };
            /**
             * @description Tên trường nói đúng nó là gì, và **mỗi số tiền đi kèm đơn vị**.
             *     `floor_cpm` là giá cho 1.000 lượt hiển thị; `io_rate` là giá thuê
             *     một kỳ, kỳ nói ở `io_rate.unit`.
             *
             *     Bản đầu trả `floor_cpm_vnd` bằng cách làm tròn `floor_cpm` và bỏ
             *     qua `floor_cpm_currency` — cột đó nhận VND hoặc USD, nên một hàng
             *     USD 2,50 ra ngoài thành "3 VND" (Codex R39). API **không** tự quy
             *     đổi: quy đổi cần một chính sách tỷ giá có người chốt.
             *
             *     `io_rate` không có cột currency trong CSDL nên luôn là VND; trường
             *     `currency` vẫn có mặt để giả định đó nhìn thấy được.
             *
             *     v1 có `price_per_slot_vnd` trả giá CPM dưới cái tên "giá một slot" —
             *     v2 không lặp lại.
             */
            pricing: {
                /** @enum {string|null} */
                model: "cpm" | "io" | "both" | null;
                floor_cpm: {
                    /** @description Có thể là số lẻ khi currency không phải VND. */
                    amount: number | null;
                    /** @enum {string} */
                    currency: "VND" | "USD";
                };
                io_rate: {
                    amount: number | null;
                    /** @enum {string} */
                    currency: "VND";
                    /** @enum {string|null} */
                    unit?: "week" | "month" | null;
                };
            };
            photo_url?: string | null;
        };
        /**
         * @description Danh sách trắng. Không bao giờ chứa `revenue_share_pct`, `billing_info`,
         *     `bank_*`, `tax_code` hay `business_license_path`.
         */
        OwnerSummary: {
            slug: string;
            name: string;
            type?: string | null;
            cover_url?: string | null;
            screen_count?: number | null;
        };
        /**
         * @description Bộ trường lấy đúng bằng những gì trang owner công khai đang hiển thị,
         *     không thêm. Không bao giờ chứa `revenue_share_pct`, `billing_info`,
         *     `bank_*`, `tax_code`, `business_license_path` hay `legal_*`.
         */
        OwnerDetail: {
            slug: string;
            name: string;
            type?: string | null;
            tagline?: string | null;
            about?: string | null;
            logo_url?: string | null;
            cover_url?: string | null;
            /** @description Thông tin liên hệ doanh nghiệp, đã công khai trên trang owner. */
            contact?: {
                website?: string | null;
                email?: string | null;
                phone?: string | null;
                address?: string | null;
            };
            location?: {
                province?: string | null;
                commune?: string | null;
            };
            founded?: string | number | null;
            stats: {
                screen_count: number;
                city_count: number;
                venue_types: string[];
            };
        };
        /**
         * @description Danh sách trắng. **Không có `id`** — trang Blade dùng `$product->id`
         *     cho form giỏ hàng, API dùng `slug`; khóa nội bộ không ra ngoài.
         *
         *     Về tên trường giá: cột trong CSDL tên `floor_price`, nhưng với sản phẩm
         *     dạng gói đó chính là **giá người mua trả cho cả gói**, không phải giá
         *     sàn nội bộ — `BundleExpander::productTotal()` lấy đúng cột này và trang
         *     sản phẩm đã hiển thị nó công khai. Ở đây đặt tên nói đúng nó là gì
         *     (`package`, `per_screen`) thay vì chép lại một cái tên gây hiểu sai.
         */
        ProductSummary: {
            slug: string;
            name: string;
            /** @enum {string} */
            type: "single" | "package" | "custom";
            category: {
                code?: string | null;
                label?: string | null;
            };
            /** @description Cách bán — chỉ gói, chỉ lẻ, hay cả hai. */
            listing_mode: {
                /** @enum {string|null} */
                code?: "package_only" | "individual_only" | "both" | null;
                label?: string | null;
                allows_package?: boolean;
                allows_individual?: boolean;
            };
            owner?: {
                slug?: string | null;
                name?: string | null;
            };
            location?: {
                city?: string | null;
                region?: string | null;
                site?: string | null;
            };
            network?: {
                name?: string;
            } | null;
            quantity?: {
                total_units?: number | null;
                min?: number | null;
                max?: number | null;
                screen_count?: number | null;
            };
            /**
             * @description Mỗi số tiền đi kèm `currency`, lấy từ cột `products.currency`.
             *     Không giả định VND — đó đúng là lỗi R39 đã bắt ở màn hình.
             */
            pricing: {
                currency: string;
                /** @enum {string|null} */
                unit?: "month" | "week" | "day" | "campaign" | null;
                /** @description Giá cả gói. */
                package?: number | null;
                /** @description Giá một màn hình khi mua lẻ; rỗng nghĩa là không bán lẻ. */
                per_screen?: number | null;
                package_discount_pct?: number | null;
            };
            short_description?: string | null;
            cover_url?: string | null;
            featured?: boolean;
        };
        ProductDetail: components["schemas"]["ProductSummary"] & {
            description?: string | null;
            photo_urls?: string[];
            /**
             * @description JSON tự do do quản trị nhập, đã hiển thị công khai trên trang
             *     sản phẩm. Không whitelist được theo khóa vì bộ khóa đổi theo
             *     từng loại sản phẩm, nên **bất cứ gì nhập vào đây đều là công
             *     khai** — chỗ phải chặn là lúc nhập, không phải lúc trả.
             */
            specs?: Record<string, never> | null;
            /** @description Whitelist theo khóa, không trả nguyên blob JSON. */
            package_options?: {
                name?: string | null;
                quantity?: number | null;
                price?: number | null;
            }[];
            screens?: components["schemas"]["ScreenSummary"][];
            seo?: {
                meta_title?: string | null;
                meta_description?: string | null;
            };
        };
        /**
         * @description `rate_snapshot` **không** có trong DTO này. Đó là ảnh chụp cấu hình giá
         *     của media owner lúc thêm giỏ, dùng để phát hiện giá đổi trước khi chốt
         *     đơn — nó mang nguyên cấu hình kho, không phải thứ người mua cần thấy.
         */
        Cart: {
            items: components["schemas"]["CartItem"][];
            summary: {
                /** @enum {string} */
                currency: "VND";
                item_count: number;
                /**
                 * @description **Chưa gồm VAT.** VAT tính một chỗ duy nhất ở
                 *     `PaymentService::withVat()`, lúc chốt đơn — cộng VAT ở đây là
                 *     một phép làm tròn thứ hai, và hai chỗ làm tròn khác nhau là
                 *     cách sinh ra "công nợ bằng 0 nhưng chưa trả đủ".
                 */
                subtotal: number;
                impressions?: number;
            };
        };
        CartItem: {
            /**
             * @description Dòng giỏ **có** `id` trong khi các DTO công khai thì không. Cố ý:
             *     client phải gọi được PATCH/DELETE lên đúng dòng này, và nó là dữ
             *     liệu riêng của chính người đang đăng nhập chứ không phải khóa của
             *     tài nguyên dùng chung.
             */
            id: string;
            screen?: components["schemas"]["ScreenSummary"] | null;
            product?: {
                slug?: string;
                name?: string;
            } | null;
            /** @enum {string|null} */
            buy_mode?: "package" | "individual" | null;
            period: {
                /** Format: date */
                start_date?: string | null;
                /** Format: date */
                end_date?: string | null;
            };
            delivery?: {
                /** @enum {string|null} */
                pricing_model?: "cpm" | "io" | null;
                share_of_voice_pct?: number | null;
                spot_length?: number | null;
                booked_cpms?: number | null;
                duration_units?: number | null;
                duration_unit?: string | null;
            };
            /** @description Do máy chủ tính. Không nhận chiều ngược lại. */
            estimate: {
                /** @enum {string} */
                currency: "VND";
                cost?: number | null;
                impressions?: number | null;
                duration_discount_pct?: number | null;
            };
            notes?: string | null;
        };
        /**
         * @description Cố tình gọn: bản đồ trả hàng trăm bản ghi một lúc nên mỗi trường thừa
         *     nhân lên hàng trăm lần. Cần đầy đủ thì gọi `/api/v2/screens/{slug}`.
         */
        MapPin: {
            slug: string;
            name: string;
            lat: number;
            lng: number;
            city?: string | null;
            address?: string | null;
            owner?: {
                slug?: string | null;
                name?: string | null;
            };
            /**
             * @description Giá hiển thị kèm **đơn vị đo** (`unit`) và **đơn vị tiền**
             *     (`currency`). `io_rate` nếu bán theo kỳ, ngược lại là giá CPM —
             *     hai thang đo khác nhau, nên thiếu `unit` là mời so nhầm, và giá
             *     CPM có thể lưu bằng USD nên thiếu `currency` là gắn nhãn sai
             *     (Codex R39).
             */
            price?: {
                amount: number | null;
                /** @enum {string} */
                currency: "VND" | "USD";
                unit?: string | null;
            };
            photo_url?: string | null;
        };
        FilterFacet: {
            code: string | null;
            name: string | null;
            count: number;
        };
        /** @description Suất còn lại tính thật, gồm cả suất người khác đang giữ trong giỏ. */
        Availability: {
            window_days: number;
            remaining_sov_pct: number;
            has_capacity: boolean;
        };
        PageMeta: {
            page: number;
            per_page: number;
            total: number;
            last_page: number;
            max_per_page: number;
        };
        /** @description Định dạng lỗi thống nhất cho mọi endpoint v2. */
        Error: {
            error: string;
            message: string;
            code: number;
            details: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: {
        /** @description Không tìm thấy */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Dữ liệu gửi lên không hợp lệ */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Vượt giới hạn tần suất. Phản hồi giữ nguyên `Retry-After` và các
         *     header hạn mức của `ThrottleRequests` — đổi định dạng body không được
         *     phá thông tin điều khiển của giao thức (Codex R41).
         */
        TooManyRequests: {
            headers: {
                /** @description Số giây nên chờ trước khi gọi lại. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Chưa đăng nhập. Dùng **đúng** định dạng lỗi thống nhất, kể cả ở mã
         *     này — bên tiêu thụ không phải viết một nhánh đặc biệt cho 401.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Yêu cầu hợp lệ nhưng trạng thái hiện tại không cho phép — ví dụ suất
         *     phát sóng đã hết, hoặc giá của media owner đã đổi kể từ lúc thêm giỏ.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Lỗi phía máy chủ, vẫn theo định dạng lỗi thống nhất. Thông điệp chi
         *     tiết chỉ xuất hiện khi `app.debug` bật; production trả câu chung và
         *     không bao giờ có stack trace.
         */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
